# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yemeksepeti' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "Firebase/Analytics"
  pod "Firebase/Auth"  

  # Pods for yemeksepeti

  target 'yemeksepetiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'yemeksepetiUITests' do
    # Pods for testing
  end

end
